/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.iesapp.apps.administrador.wizard.clientchange;

import org.iesapp.apps.administrador.wizard.noucurs.*;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import org.iesapp.apps.administrador.Cfg;
import org.iesapp.framework.util.CoreCfg;

/**
 *
 * @author Josep
 */
public class Step5 extends javax.swing.JPanel {
    private DefaultListModel model1, model2;
    private DefaultComboBoxModel combomodel1;
    private HashMap<String, String> taules;
    private final Cfg cfg;

    /**
     * Creates new form StartupStep3
     */
    public Step5(final Cfg cfg) {
        this.cfg = cfg;
        initComponents();
        relatedTables1.startUp(cfg);
     
    }
    
    public void updateComponents()
    {
        relatedTables1.setTables(new String[]{ "xes_alumne","xes_alumne_historic","xes_alumne_detall","xes_dades_pares","xes_alta" },
                CoreCfg.core_mysqlDBPrefix);
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        relatedTables1 = new org.iesapp.apps.administrador.wizard.noucurs.RelatedTables();
        jLinkButton1 = new com.l2fprod.common.swing.JLinkButton();
        jLinkButton2 = new com.l2fprod.common.swing.JLinkButton();
        jLinkButton3 = new com.l2fprod.common.swing.JLinkButton();

        jLinkButton1.setText("-     Importar alumnes (a partir de fulls EXCEL descarregades del Xestib2.0)");
        jLinkButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLinkButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLinkButton1ActionPerformed(evt);
            }
        });

        jLinkButton2.setText("-     Importar fotos dels alumnes (a partir de pàgines WEB descarregades del Xestib2.0)");
        jLinkButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLinkButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLinkButton2ActionPerformed(evt);
            }
        });

        jLinkButton3.setText("-     Genera contrasenyes dels nous alumnes");
        jLinkButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLinkButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLinkButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(relatedTables1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLinkButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLinkButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLinkButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLinkButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLinkButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLinkButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 377, Short.MAX_VALUE)
                .addComponent(relatedTables1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLinkButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkButton1ActionPerformed
        org.iesapp.modules.fitxes.dialogs.admin.ImportarAlumnes dlg = new org.iesapp.modules.fitxes.dialogs.admin.ImportarAlumnes(null,false,cfg.getCoreCfg().anyAcademic, cfg.getFitxesCfg());
        dlg.setLocationRelativeTo(null);
        dlg.setAlwaysOnTop(true);
        dlg.setVisible(true);
    }//GEN-LAST:event_jLinkButton1ActionPerformed

    private void jLinkButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkButton2ActionPerformed
        org.iesapp.framework.admin.ImportarFotos dlg = new org.iesapp.framework.admin.ImportarFotos(null,false, cfg.getCoreCfg());
        dlg.setLocationRelativeTo(null);
        dlg.setAlwaysOnTop(true);
        dlg.setVisible(true);
    }//GEN-LAST:event_jLinkButton2ActionPerformed

    private void jLinkButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkButton3ActionPerformed
       org.iesapp.framework.admin.GenContrassenyes dlg = new  org.iesapp.framework.admin.GenContrassenyes(null,false,""+cfg.getCoreCfg().anyAcademic, cfg.getCoreCfg());
       dlg.setLocationRelativeTo(null);
       dlg.setAlwaysOnTop(true);
       dlg.setVisible(true);
    }//GEN-LAST:event_jLinkButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private com.l2fprod.common.swing.JLinkButton jLinkButton1;
    private com.l2fprod.common.swing.JLinkButton jLinkButton2;
    private com.l2fprod.common.swing.JLinkButton jLinkButton3;
    private org.iesapp.apps.administrador.wizard.noucurs.RelatedTables relatedTables1;
    // End of variables declaration//GEN-END:variables

   
}
