/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.iesapp.apps.administrador.actions;

 
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import org.iesapp.apps.administrador.Cfg;
import org.iesapp.apps.administrador.bimodules.GestionaAlumnes;
import org.iesapp.framework.util.CoreCfg;

/**
 *
 * @author Josep
 */
public class CanviaFoto extends javar.JRDialog {
    private int exp2;
    private java.io.File file = null;
    private final Cfg cfg;
    /**
     * Creates new form CanviaFoto
     */
    public CanviaFoto(java.awt.Frame parent, boolean modal, Cfg cfg) {
        super(parent, modal);
        this.cfg = cfg;
        initComponents();
       
    }

    public void StartUp(byte[] foto, int exp2)
    {
        this.exp2 = exp2;
        Icon icon0 = GestionaAlumnes.createIcon(foto, jLabel3.getHeight());
        jLabel3.setIcon(icon0);
        jLabel4.setIcon(icon0);
    }
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Foto de l'alumne/a");

        jLabel1.setText("Foto antiga");

        jLabel2.setText("Foto Nova");

        jButton1.setText("Cancel·la");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Canvia");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton3.setText("Aplica i tanca");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    //Canvia la foto
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       //Obrir el fitxer
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Selecciona una imatge ...");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);          
        
        FileFilter filter = new FileFilter() {
            public boolean accept(File pathname) {
                String name = pathname.getAbsolutePath();
                return  name.endsWith(".jpg") || name.endsWith(".gif") || name.endsWith(".png")  ;
            }

            @Override
            public String getDescription() {
                return "Fitxers d'imatge";
            }
        };
          
          chooser.setFileFilter(filter);
        	          
	 if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
//        
          double ratio = jLabel3.getHeight() / (1.*jLabel3.getWidth());
          try {
                file = chooser.getSelectedFile();
                BufferedImage img = ImageIO.read(file);
                int w = 1;
                int h = 1;
                if(img.getWidth()>=img.getHeight()) //apaisada
                {
                    h = img.getHeight();
                    w = (int) (h / ratio);
                }
                else
                {
                    w = img.getWidth();
                    h = (int) (w* ratio);
                }
                
                Image scaledInstance = img.getSubimage(0, 0, w, h).getScaledInstance(-1, jLabel3.getHeight(), Image.SCALE_SMOOTH);
                jLabel4.setIcon(new ImageIcon(scaledInstance));
          } catch (IOException e) {
          }

         }  
          
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

         if(file==null) {
            return;
        }
        
         int maxHeight = 70; //Evita fotos massa grans a la base de dades
         
         double ratio = jLabel3.getHeight() / (1.*jLabel3.getWidth());
         try {               
                BufferedImage img = ImageIO.read(file);
                int w = 1;
                int h = 1;
                if(img.getWidth()>=img.getHeight()) //apaisada
                {
                    h = img.getHeight();
                    w = (int) (h / ratio);
                }
                else
                {
                    w = img.getWidth();
                    h = (int) (w* ratio);
                }
                
                Image scaledInstance = img.getSubimage(0, 0, w, h).getScaledInstance(-1, maxHeight, Image.SCALE_SMOOTH);
                BufferedImage buffered = toBufferedImage(scaledInstance);
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                ImageIO.write(buffered, "jpg", baos);
		baos.flush();
                byte[] data = baos.toByteArray();
		baos.close();
                
                String SQL2 = "UPDATE `"+CoreCfg.core_mysqlDBPrefix+"`.xes_alumne_detall SET Foto=? WHERE Exp_FK_ID="+exp2;
            
                Connection con = cfg.getCoreCfg().getMysql().getConnection();
                //con.setAutoCommit(false);
                PreparedStatement ps = con.prepareStatement(SQL2); 
                ps.setBytes(1, data);
                int s = ps.executeUpdate();
                    

                
          } catch (SQLException ex) {
                Logger.getLogger(CanviaFoto.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException e) {
          }
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

     private static BufferedImage toBufferedImage(Image src) {
        int w = src.getWidth(null);
        int h = src.getHeight(null);
        int type = BufferedImage.TYPE_INT_RGB;  // other options
        BufferedImage dest = new BufferedImage(w, h, type);
        Graphics2D g2 = dest.createGraphics();
        g2.drawImage(src, 0, 0, null);
        g2.dispose();
        return dest;
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
