/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.iesapp.apps.administrador.actions;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import org.iesapp.apps.administrador.Cfg;
import org.iesapp.apps.administrador.wizard.noucurs.Step1;
import org.iesapp.framework.util.CoreCfg;

/**
 *
 * @author Josep
 */
public class CanviAnyAcademic extends javar.JRDialog {

    public static final byte ACCEPT = 1;
    public static final byte CANCEL = 0;
    protected byte exitCode=0;
    private final Cfg cfg;
    /**
     * Creates new form CanviAnyAcademic
     */
    public CanviAnyAcademic(java.awt.Frame parent, boolean modal, Cfg cfg) {
        super(parent, modal);
        this.cfg = cfg;
        initComponents();
        
        jLabel2.setText(CoreCfg.core_mysqlDBPrefix);
        
        DefaultComboBoxModel model1 = new DefaultComboBoxModel();
        
          //determina els cursos que existeixen
        cfg.getCoreCfg().getMysql().setCatalog(CoreCfg.core_mysqlDBPrefix);
        String SQL1 = "Show databases";
        ResultSet rs1 = cfg.getCoreCfg().getMysql().getResultSet(SQL1);
        try {
            while(rs1!=null && rs1.next())   
            {
                String txt = rs1.getString(1);
                if(txt.startsWith(CoreCfg.core_mysqlDBPrefix))
                {
                    txt = txt.replaceAll(CoreCfg.core_mysqlDBPrefix, "").trim();
                    if(!txt.isEmpty()) {
                        model1.addElement(txt);
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Step1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        jComboBox1.setModel(model1);
        jComboBox1.setSelectedItem(cfg.getCoreCfg().anyAcademic+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setTitle("Canvi d'any acadèmic");

        jButton1.setText("Cancel·la");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Accepta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Anys academics en la base iesDigital:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("nomdelabase");

        jLabel3.setText("Seleccionau un any (corresponent a l'inici del curs escolar)");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Atenció: El canvi d'any es propagarà a tots els clients.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(0, 7, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        exitCode = CANCEL;
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        exitCode = ACCEPT;
        
        if(jComboBox1.getSelectedIndex()<0) {
            return;
        }
        
        String sany = (String) jComboBox1.getSelectedItem();
        int nouAny = Integer.parseInt(sany);
        if(cfg.getCoreCfg().anyAcademic!=nouAny)
        {
            cfg.getCoreCfg().anyAcademic = nouAny;
            CoreCfg.configTableMap.put("anyIniciCurs", sany);
            cfg.getCoreCfg().updateDatabaseCfg("anyIniciCurs", sany);
            CoreCfg.core_mysqlDB = CoreCfg.core_mysqlDBPrefix + sany;
            cfg.getCoreCfg().getMysql().setCatalog(CoreCfg.core_mysqlDB);
            CoreCfg.coreDB_sgdDB = CoreCfg.configTableMap.get("sgdDBPrefix") + sany;
            cfg.getCoreCfg().getSgd().setCatalog(CoreCfg.coreDB_sgdDB);
            System.out.println("nous catalogs are "+CoreCfg.core_mysqlDB+" and "+ CoreCfg.coreDB_sgdDB);
        }
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    public byte getExitCode() {
        return exitCode;
    }
}
