/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.iesapp.apps.administrador.jasperreports;

import java.util.HashMap;
import javax.swing.JLabel;

/**
 *
 * @author Josep
 */
public class FixDlg extends javar.JRDialog {
    private final JasperReportParser jrp;

    /**
     * Creates new form FixDlg
     */
    public FixDlg(java.awt.Frame parent, boolean modal, JasperReportParser jrp, HashMap<String,String> map) {
        super(parent, modal);
        initComponents();
        this.jrp = jrp;
        fillView(map);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Errors and Warnings");

        jLabel1.setText("Errors");

        jLabel2.setText("Warnings");

        jPanel1.setLayout(new com.l2fprod.common.swing.PercentLayout());
        jScrollPane1.setViewportView(jPanel1);

        jPanel2.setLayout(new com.l2fprod.common.swing.PercentLayout());
        jScrollPane2.setViewportView(jPanel2);

        jButton1.setText("FIX");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(0, 284, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if(!jrp.checkExistence())
         {
             return;
         }
         jrp.fix();
         HashMap<String, String> result = jrp.checkParameters();
         fillView(result);
    }//GEN-LAST:event_jButton1ActionPerformed

     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void fillView(HashMap<String, String> map) {
        jPanel1.removeAll();
        jPanel2.removeAll();
        int nerr = 0;
        for(String key: map.keySet())
        {
            String get = map.get(key);
            if(get.contains("ERROR"))
            {
                nerr +=1;
                JLabel jLinkButton = new JLabel(get);
                jPanel1.add(jLinkButton);
            }
            else if(get.contains("WARNING"))
            {
                JLabel jLinkButton = new JLabel(get);
                jPanel2.add(jLinkButton);
            }
        }
        jPanel1.revalidate();
        jPanel2.revalidate();
        jPanel1.repaint();
        jPanel2.repaint();
        jButton1.setEnabled(nerr>0);        
    }
}
