/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.iesapp.apps.administrador.bimodules;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.iesapp.apps.administrador.Cfg;
import org.iesapp.clients.iesdigital.dates.Avaluacions;
import org.iesapp.framework.pluggable.TopModuleWindow;

/**
 *
 * @author Josep
 */
public class AvaluacionsManager extends TopModuleWindow {
    private final DefaultListModel modelList1;
    private ArrayList<Avaluacions> allAvaluacions;
    private boolean listening = false;
    private Cfg cfg;
    
    /**
     * Creates new form AvaluacionsManager
     */
    public AvaluacionsManager() {
        
        this.moduleDescription = "Avaluacions manager";
        this.moduleDisplayName = "Avaluacions manager";
        this.moduleName = "avaluacionsManager";
        initComponents();
        
        
        PropertyChangeListener propertyChangeListener = new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                try {
                    if (evt.getPropertyName().equals("date")) {
                        
                        if(listening)
                        {
                            updateAvaluacio();
                        }
                    }
                } catch (Exception e) {
                }
            }
        };
        jDateChooser1ini.addPropertyChangeListener(propertyChangeListener);
        jDateChooser1fi.addPropertyChangeListener(propertyChangeListener);
        jDateChooser2ini.addPropertyChangeListener(propertyChangeListener);
        jDateChooser2fi.addPropertyChangeListener(propertyChangeListener);
        jDateChooser3ini.addPropertyChangeListener(propertyChangeListener);
        jDateChooser3fi.addPropertyChangeListener(propertyChangeListener);


        modelList1 = new DefaultListModel();
        jList1.setModel(modelList1);
    }
    
    @Override
    public void postInitialize() {
        cfg = (Cfg) getInitializationObject();
        System.out.println("postinitialize"+cfg);
        fillList();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuDuplicate = new javax.swing.JMenuItem();
        jMenuRemove = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jDateChooser1ini = new com.toedter.calendar.JDateChooser();
        jDateChooser2ini = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser3fi = new com.toedter.calendar.JDateChooser();
        jDateChooser3ini = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jDateChooser2fi = new com.toedter.calendar.JDateChooser();
        jDateChooser1fi = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();

        jMenuDuplicate.setText("Duplicate");
        jMenuDuplicate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDuplicateActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuDuplicate);

        jMenuRemove.setText("Remove");
        jMenuRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRemoveActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuRemove);

        jLabel1.setText("Ambits");

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel6.setText("Fi");

        jLabel4.setText("3a");

        jLabel7.setText("Ensenyament");

        jLabel5.setText("Inici");

        jLabel8.setText("Estudis");

        jLabel2.setText("1a");

        jTextField1.setEditable(false);
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });

        jLabel3.setText("2a");

        jTextField2.setEditable(false);
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });

        jLabel9.setText("Per un correcte funcionament, les avaluacions no poden tenir dies en comu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jDateChooser1ini, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(140, 140, 140))
                            .addComponent(jDateChooser1fi, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(49, 49, 49)
                            .addComponent(jTextField2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jDateChooser2ini, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jDateChooser2fi, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jDateChooser3ini, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jDateChooser3fi, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel9)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1fi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jDateChooser1ini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jDateChooser2fi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDateChooser2ini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser3fi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser3ini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentContainer());
        getContentContainer().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        AmbitsChooser dlg = new AmbitsChooser(javar.JRDialog.getActiveFrame(), AmbitsChooser.CHOOSER_ENSENYAMENT, jTextField1.getText(), cfg);
        dlg.setLocationRelativeTo(jTextField1);
        byte showModal = dlg.showModal();
        if (showModal == AmbitsChooser.CHOOSER_ACCEPT) {
            jTextField1.setText(dlg.getSelection());
            int row = jList1.getSelectedIndex();
            if (row >= 0) {
                allAvaluacions.get(row).setEnsenyament(dlg.getSelection());
                modelList1.setElementAt(jTextField1.getText() + " | " + jTextField2.getText(), row);
                updateAvaluacio();
            }
        }
        dlg.dispose();
        checkOverlap();
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        AmbitsChooser dlg = new AmbitsChooser(javar.JRDialog.getActiveFrame(),AmbitsChooser.CHOOSER_ESTUDIS,jTextField2.getText(),cfg);
        dlg.setLocationRelativeTo(jTextField2);
        byte showModal = dlg.showModal();
        if(showModal==AmbitsChooser.CHOOSER_ACCEPT)
        {
            jTextField2.setText(dlg.getSelection());
            int row = jList1.getSelectedIndex();
            if(row>=0)
            {
                allAvaluacions.get(row).setEstudis(dlg.getSelection());
                modelList1.setElementAt(jTextField1.getText()+" | "+jTextField2.getText(), row);
                updateAvaluacio();
            }
        }
        dlg.dispose();
        checkOverlap();
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        int row = jList1.getSelectedIndex();  
        if(row<0)
        {
            return;
        }
        fillPanel();
    }//GEN-LAST:event_jList1ValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Avaluacions aval = new Avaluacions(cfg.getCoreCfg().getIesClient());
        aval.save();
        fillList();
        jList1.setSelectedIndex(modelList1.getSize()-1);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row = jList1.getSelectedIndex();
        if(row<0)
        {
            return;
        }
        int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Do you want to delete this?");
        if(showConfirmDialog==JOptionPane.YES_OPTION)
        {
            allAvaluacions.get(row).delete();
            fillList();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuDuplicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDuplicateActionPerformed
       int row = jList1.getSelectedIndex();
       if(row<0)
       {
           return;
       }
       allAvaluacions.get(row).duplicate();
       fillList();
       jList1.setSelectedIndex(modelList1.getSize()-1);
    }//GEN-LAST:event_jMenuDuplicateActionPerformed

    private void jMenuRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRemoveActionPerformed
       int row = jList1.getSelectedIndex();
       if(row<0)
       {
           return;
       }
       allAvaluacions.get(row).delete();
       fillList();
        
    }//GEN-LAST:event_jMenuRemoveActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
         if(evt.getButton()==MouseEvent.BUTTON3)
         {
             jPopupMenu1.show(this, evt.getX(), evt.getY());
         }
    }//GEN-LAST:event_jList1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1fi;
    private com.toedter.calendar.JDateChooser jDateChooser1ini;
    private com.toedter.calendar.JDateChooser jDateChooser2fi;
    private com.toedter.calendar.JDateChooser jDateChooser2ini;
    private com.toedter.calendar.JDateChooser jDateChooser3fi;
    private com.toedter.calendar.JDateChooser jDateChooser3ini;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JMenuItem jMenuDuplicate;
    private javax.swing.JMenuItem jMenuRemove;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    private void fillList() {
        listening = false;
        modelList1.clear();
        allAvaluacions = Avaluacions.getAllAvaluacions(cfg.getCoreCfg().anyAcademic, cfg.getCoreCfg().getIesClient());
        //System.out.println("AllAvaluacions is "+allAvaluacions);
        for(Avaluacions aval: allAvaluacions)
        {
            modelList1.addElement(aval.getEnsenyament()+" | "+aval.getEstudis());
           
        }
        
        checkOverlap();
       
        
        if(!modelList1.isEmpty())
        {
            jList1.setSelectedIndex(0);
        }
        
        if(!modelList1.isEmpty())
        {
            listening = true;
        }
        fillPanel();
        
        
        
        
    }

    private void updateAvaluacio() {
        int row = jList1.getSelectedIndex();
        if(row<0)
        {
            return;
        }
        
        Avaluacions aval = allAvaluacions.get(row);
        aval.setEnsenyament(jTextField1.getText());
        aval.setEstudis(jTextField2.getText());
        aval.getFechaInicios().put("1", jDateChooser1ini.getDate());
        aval.getFechaInicios().put("2", jDateChooser2ini.getDate());
        aval.getFechaInicios().put("3", jDateChooser3ini.getDate());
        
        aval.getFechaFins().put("1", jDateChooser1fi.getDate());
        aval.getFechaFins().put("2", jDateChooser2fi.getDate());
        aval.getFechaFins().put("3", jDateChooser3fi.getDate());
         
        aval.save();
    }

    private void fillPanel() {
        listening = false;
        jPanel1.setVisible(!modelList1.isEmpty());
        
        int row = jList1.getSelectedIndex();
        if(row<0){
            jPanel1.setVisible(false);
            return;
        }
        
        Avaluacions aval = allAvaluacions.get(row);        
        jDateChooser1ini.setDate(aval.getFechaInicios().get("1"));
        jDateChooser1fi.setDate(aval.getFechaFins().get("1"));
        jDateChooser2ini.setDate(aval.getFechaInicios().get("2"));
        jDateChooser2fi.setDate(aval.getFechaFins().get("2"));
        jDateChooser3ini.setDate(aval.getFechaInicios().get("3"));
        jDateChooser3fi.setDate(aval.getFechaFins().get("3"));
        
        jTextField1.setText(aval.getEnsenyament());
        jTextField2.setText(aval.getEstudis());
        listening = true;
    }

    private void checkOverlap() {
        boolean isthereoverlap = false;
        for(int i=0; i<modelList1.getSize(); i++)
        {
            AmbitsChooser ac = new AmbitsChooser(javar.JRDialog.getActiveFrame(), AmbitsChooser.CHOOSER_ESTUDIS,"",cfg);
            Avaluacions aval = allAvaluacions.get(i);
            isthereoverlap = ac.checkOverlap(aval.getEnsenyament(), aval.getEstudis());
        }
        jList1.setOpaque(true);
        if (isthereoverlap) {
            jList1.setBackground(Color.red);
            jList1.setToolTipText("Warning: Overlap among entries found.");
        } else {
            jList1.setBackground(Color.white);
            jList1.setToolTipText(null);
        }
           
    }
}
