/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.iesapp.apps.administrador.bimodules;

import org.iesapp.apps.mysqlbrowser.DBEditorPanel;
import org.iesapp.database.MyDatabase;
import org.iesapp.framework.pluggable.TopModuleWindow;

/**
 *
 * @author Josep
 * Wrap DBEditor panel into a module
 */
public class DBEditorModule extends TopModuleWindow {
    private final DBEditorPanel tableEditor;

    /**
     * Creates new form DBEditorModule
     */
    public DBEditorModule(String name) {
        this.moduleDescription = "A database editor for table "+name;
        this.moduleDisplayName = name;
        this.moduleName = name;
        
        initComponents();
        tableEditor = new DBEditorPanel();
        tableEditor.enableMoreOperations(false);
        this.add(tableEditor);
    }
    
    public void setTable(MyDatabase host, String database, String table)
    {
        tableEditor.setTable(host, database, table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getContentContainer().setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
