/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.iesapp.apps.administrador.bimodules;

import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import org.iesapp.apps.administrador.AdministradorGUI;
import org.iesapp.apps.administrador.Cfg;
import org.iesapp.apps.administrador.actions.CanviaFoto;
import org.iesapp.apps.administrador.actions.CanviaGrup;
import org.iesapp.apps.administrador.actions.Permisos;
import org.iesapp.clients.iesdigital.alumnat.GeneratePwds;
import org.iesapp.clients.iesdigital.fitxes.BeanDadesPersonals;
import org.iesapp.framework.admin.CanviExpedientDlg;
import org.iesapp.framework.table.MyIconLabelRenderer;
import org.iesapp.framework.util.CoreCfg;
import org.iesapp.util.StringUtils;

/**
 *
 * @author Josep
 */
public class GestionaAlumnes extends org.iesapp.framework.pluggable.TopModuleWindow {
    private DefaultTableModel modelTable1;
    private int rowHeight=45;
    private final AdministradorGUI parental;
    private final DefaultComboBoxModel comboModel1;
    private final DefaultComboBoxModel comboModel2;
    private final DefaultComboBoxModel comboModel3;
    private final Cfg cfg;

    /**
     * Creates new form GestionaAlumnes
     */
    public GestionaAlumnes(JFrame par, Cfg cfg) {
        this.cfg = cfg;
        this.moduleDescription = "Student administration";
        this.moduleDisplayName = "Gestió d'alumnes";
        this.moduleName = "gestioAlumnes";
        
        //iesapp.fitxescore.util.Cfg.Load();
        
        initComponents();
        comboModel1 = StringUtils.listAsCombo(org.iesapp.modules.fitxescore.util.Cfg.modelComboEnsenyament_tots);
        comboModel2 = StringUtils.listAsCombo(org.iesapp.modules.fitxescore.util.Cfg.modelComboEstudis_tots);
        comboModel3 = StringUtils.listAsCombo(org.iesapp.modules.fitxescore.util.Cfg.modelComboGrup_tots);
        comboModel1.insertElementAt("Tots", 0);        
        comboModel2.insertElementAt("Tots", 0);        
        comboModel3.insertElementAt("Tots", 0);        
        
        jComboBox1.setModel(comboModel1);
        jComboBox2.setModel(comboModel2);
        jComboBox3.setModel(comboModel3);
        jComboBox1.setSelectedIndex(0);        
        jComboBox2.setSelectedIndex(0);        
        jComboBox3.setSelectedIndex(0);        
        
        fillTable();
        parental = (AdministradorGUI) par;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            }};
            jTaskPane1 = new com.l2fprod.common.swing.JTaskPane();
            jTaskPaneGroup1 = new com.l2fprod.common.swing.JTaskPaneGroup();
            jLinkButton1 = new com.l2fprod.common.swing.JLinkButton();
            jLinkButton2 = new com.l2fprod.common.swing.JLinkButton();
            jLinkButton3 = new com.l2fprod.common.swing.JLinkButton();
            jLinkButton8 = new com.l2fprod.common.swing.JLinkButton();
            jTaskPaneGroup2 = new com.l2fprod.common.swing.JTaskPaneGroup();
            jLinkButton4 = new com.l2fprod.common.swing.JLinkButton();
            jLinkButton5 = new com.l2fprod.common.swing.JLinkButton();
            jTaskPaneGroup3 = new com.l2fprod.common.swing.JTaskPaneGroup();
            jLinkButton6 = new com.l2fprod.common.swing.JLinkButton();
            jLinkButton7 = new com.l2fprod.common.swing.JLinkButton();

            jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

            addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    formFocusGained(evt);
                }
            });

            jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Condicions de cerca"));

            jLabel1.setText("Ensenyament");

            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

            jLabel2.setText("Estudis");

            jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

            jLabel3.setText("Grup");

            jButton1.setText("Cercar");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jLabel4.setText("Núm Expedient");

            jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jTextField1KeyPressed(evt);
                }
            });

            jLabel5.setText("Primer llinatge");

            jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jTextField2KeyPressed(evt);
                }
            });

            jLabel6.setText("Segon llinatge");

            jTextField3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField3ActionPerformed(evt);
                }
            });
            jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jTextField3KeyPressed(evt);
                }
            });

            jLabel7.setText("Nom");

            jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jTextField4KeyPressed(evt);
                }
            });

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addGap(55, 55, 55))
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(92, 92, 92)
                    .addComponent(jButton1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 42, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addGap(1, 1, 1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2))
            );

            modelTable1 = new javax.swing.table.DefaultTableModel(
                new Object [][] {
                },
                new String [] {
                    "Exp.", "Pwd", "Grup", "Alumne/a", "Foto","Assignat a",
                    "N. cursos / N.Fitxes"
                }
            );
            jTable1.setModel(modelTable1);
            jTable1.getColumnModel().getColumn(0).setCellRenderer(new MyIconLabelRenderer());
            jTable1.getColumnModel().getColumn(2).setCellRenderer(new MyIconLabelRenderer());
            jTable1.getColumnModel().getColumn(3).setCellRenderer(new MyIconLabelRenderer());
            jTable1.getColumnModel().getColumn(4).setCellRenderer(new MyIconLabelRenderer());
            jTable1.getColumnModel().getColumn(5).setCellRenderer(new MyIconLabelRenderer());
            jTable1.getTableHeader().setReorderingAllowed(false);
            jTable1.setRowHeight(rowHeight);
            jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTable1MouseClicked(evt);
                }
            });
            jScrollPane1.setViewportView(jTable1);

            com.l2fprod.common.swing.PercentLayout percentLayout1 = new com.l2fprod.common.swing.PercentLayout();
            percentLayout1.setGap(14);
            percentLayout1.setOrientation(1);
            jTaskPane1.setLayout(percentLayout1);

            jTaskPaneGroup1.setTitle("Personal");
            com.l2fprod.common.swing.PercentLayout percentLayout4 = new com.l2fprod.common.swing.PercentLayout();
            percentLayout4.setGap(2);
            percentLayout4.setOrientation(1);
            jTaskPaneGroup1.getContentPane().setLayout(percentLayout4);

            jLinkButton1.setText("Edita dades personals");
            jLinkButton1.setEnabled(false);
            jLinkButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jLinkButton1ActionPerformed(evt);
                }
            });
            jTaskPaneGroup1.getContentPane().add(jLinkButton1);

            jLinkButton2.setText("Actualitza foto");
            jLinkButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jLinkButton2ActionPerformed(evt);
                }
            });
            jTaskPaneGroup1.getContentPane().add(jLinkButton2);

            jLinkButton3.setText("Asignacions");
            jLinkButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jLinkButton3ActionPerformed(evt);
                }
            });
            jTaskPaneGroup1.getContentPane().add(jLinkButton3);

            jLinkButton8.setText("Canvia # expedient");
            jLinkButton8.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jLinkButton8ActionPerformed(evt);
                }
            });
            jTaskPaneGroup1.getContentPane().add(jLinkButton8);

            jTaskPane1.add(jTaskPaneGroup1);
            jTaskPaneGroup1.getAccessibleContext().setAccessibleName("jTaskPane1");

            jTaskPaneGroup2.setTitle("Grups");
            com.l2fprod.common.swing.PercentLayout percentLayout5 = new com.l2fprod.common.swing.PercentLayout();
            percentLayout5.setGap(2);
            percentLayout5.setOrientation(1);
            jTaskPaneGroup2.getContentPane().setLayout(percentLayout5);

            jLinkButton4.setText("Canvi de grup");
            jLinkButton4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jLinkButton4ActionPerformed(evt);
                }
            });
            jTaskPaneGroup2.getContentPane().add(jLinkButton4);

            jLinkButton5.setText("Dóna de baixa");
            jLinkButton5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jLinkButton5ActionPerformed(evt);
                }
            });
            jTaskPaneGroup2.getContentPane().add(jLinkButton5);

            jTaskPane1.add(jTaskPaneGroup2);

            jTaskPaneGroup3.setTitle("Dades");
            com.l2fprod.common.swing.PercentLayout percentLayout6 = new com.l2fprod.common.swing.PercentLayout();
            percentLayout6.setGap(2);
            percentLayout6.setOrientation(1);
            jTaskPaneGroup3.getContentPane().setLayout(percentLayout6);

            jLinkButton6.setText("Genera contrasenya");
            jLinkButton6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jLinkButton6ActionPerformed(evt);
                }
            });
            jTaskPaneGroup3.getContentPane().add(jLinkButton6);

            jLinkButton7.setText("Genera fitxes");
            jLinkButton7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jLinkButton7ActionPerformed(evt);
                }
            });
            jTaskPaneGroup3.getContentPane().add(jLinkButton7);

            jTaskPane1.add(jTaskPaneGroup3);

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jTaskPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)))
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTaskPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );
        }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       fillTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        int col = jTable1.getSelectedColumn();
        if(row<0 || evt.getClickCount()<2 || evt.getButton()!=MouseEvent.BUTTON1) {
            return;
        }
        int exp2 = parseExpd(row);
       
        if(col==0)
        {
             cfg.getFitxesCfg().donaBaixa(exp2);
             fillTable();
        }        
        if(col==1)
        {
            generatePwd(exp2);
        }
        else if(col ==2)
        {
            switchGrups(exp2);
        }
        else if(col ==3)
        {
            editaFitxa(exp2);
        }       
        else if(col ==4)
        {
            canviaFoto();
        }
        else if(col==5)
        {
            String str = ((JLabel) jTable1.getValueAt(row,5)).getText() ;
            assignaTutors(exp2, str);
        }  
        else if(col ==6)
        {
            
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    //Edita dades personals
    private void jLinkButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkButton1ActionPerformed
        int row = jTable1.getSelectedRow();
        if(row<0) {      
            return;
        }      
        int exp2 = parseExpd(row); 
        
        editaFitxa(exp2);
     
    }//GEN-LAST:event_jLinkButton1ActionPerformed

    private void editaFitxa(int exp2)
    {
//          for(int i=0; i< parental.jrTabbedPane1.getTabCount(); i++)
//        {
//            if( parental.jrTabbedPane1.getComponentAt(i).getClass().equals(iesapp.administrador.actions.Fitxa.class))
//            {
//                 parental.jrTabbedPane1.setSelectedIndex(i);
//                Fitxa fitxa = (Fitxa)  parental.jrTabbedPane1.getComponentAt(i);
//                fitxa.addFitxa(exp2);
//                return;
//            }
//        }
//        
//        parental.jrTabbedPane1.addTab(new Fitxa(exp2),"Dades Personals",null,true);
//        parental.jrTabbedPane1.setSelectedIndex(parental.jrTabbedPane1.getTabCount()-1);
    }
    
    //Canvi de grup
    private void jLinkButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkButton4ActionPerformed
        int row = jTable1.getSelectedRow();
        if(row<0) {
            return;
        }
        int exp2 = parseExpd(row);
        
        switchGrups(exp2);
    }//GEN-LAST:event_jLinkButton4ActionPerformed

    private void switchGrups(int exp2)
    {
        CanviaGrup dlg = new CanviaGrup(javar.JRDialog.getActiveFrame(), true, exp2, cfg);
        dlg.setLocationRelativeTo(null);
        dlg.setVisible(true);
        
        fillTable();
    }
    
    //Permisos
    private void jLinkButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkButton3ActionPerformed
        int row = jTable1.getSelectedRow();
        if(row<0) {
            return;
        }
        String str = ((JLabel) jTable1.getValueAt(row,5)).getText() ;
        
        int exp2 = parseExpd(row);
      
        assignaTutors(exp2, str);
        
    }//GEN-LAST:event_jLinkButton3ActionPerformed

    private void assignaTutors(int exp2, String str)
    {
          
        Permisos dlg = new Permisos(parental, true, str, cfg);
        dlg.setLocationRelativeTo(null);
        dlg.setVisible(true);
        dlg.doUpdate(exp2);
        dlg.dispose();
        
        fillTable();
    }
    
    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        fillTable();
    }//GEN-LAST:event_formFocusGained

    //Dóna de baixa
    private void jLinkButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkButton5ActionPerformed
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            return;
        }
        int exp2 = parseExpd(row);
        
        cfg.getFitxesCfg().donaBaixa(exp2);

        fillTable();

    }//GEN-LAST:event_jLinkButton5ActionPerformed

    //Gen contrasenya
    private void jLinkButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkButton6ActionPerformed
        int row = jTable1.getSelectedRow();
        if(row<0) {
            return;
        }
        int exp2 = parseExpd(row);
       
        generatePwd(exp2);
    }//GEN-LAST:event_jLinkButton6ActionPerformed

    private void generatePwd(int exp2)
    {
        String msg = GeneratePwds.genContrasenya(exp2, cfg.getCoreCfg().getMysql());
        JOptionPane.showMessageDialog(javar.JRDialog.getActiveFrame(), msg);
        
        fillTable();
    }
    
    //Gen Fitxes
    private void jLinkButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkButton7ActionPerformed
   
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            return;
        }
        int exp2 = parseExpd(row);

        //Cerca a l'historic quants d'anys té creats
        String SQL1 = "SELECT xh.AnyAcademic, fitxa.Exp_FK_ID FROM `"+CoreCfg.core_mysqlDBPrefix+"`.xes_alumne_historic AS xh  LEFT JOIN "
                + " `"+CoreCfg.core_mysqlDBPrefix+"`.fitxa_alumne_curs AS fitxa ON (xh.Exp2 = fitxa.Exp_FK_ID "
                + " AND xh.AnyAcademic = fitxa.IdCurs_FK_ID) WHERE xh.exp2=" + exp2;

        ResultSet rs1 = cfg.getCoreCfg().getMysql().getResultSet(SQL1);
        ArrayList<Integer> falten = new ArrayList<Integer>();
        String msg= "";
        try {
            while (rs1 != null && rs1.next()) {
                int any = rs1.getInt("anyAcademic");
                boolean creat = rs1.getString("Exp_FK_ID") != null;
                if(!creat) {
                    falten.add(any);
                }
                msg += "Curs "+any+ " --> Fitxa "+ (creat?"Creada":"No Creada")+"\n";
            }
            if (rs1 != null) {
                rs1.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(GestionaAlumnes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(falten.isEmpty())
        {
            JOptionPane.showMessageDialog(this, msg+ "No cal fer res.");
        }
        else
        {
            
            
            Object[] options = {"No", "Sí"};
            String missatge = msg+"Voleu crear les "+falten.size()+" fitxes que falten?";

            int n = JOptionPane.showOptionDialog(javar.JRDialog.getActiveFrame(),
            missatge, "Confirmació",
            JOptionPane.INFORMATION_MESSAGE,
            JOptionPane.WARNING_MESSAGE,
            null,
            options,
            options[0]);

            if( n!=1) {
                return;
            }
        
            //Crea les fitxes
            for(int i=0; i<falten.size(); i++)
            {
                int any = falten.get(i);
                BeanDadesPersonals bean = new BeanDadesPersonals(cfg.getCoreCfg().getIesClient());
                bean.setExpedient(exp2);
                bean.createFitxaCurs(exp2, any+"-"+(any+1));
            }
            
            
        }

    }//GEN-LAST:event_jLinkButton7ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            fillTable();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            fillTable();
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            fillTable();
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            fillTable();
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jLinkButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkButton2ActionPerformed
       canviaFoto();
    }//GEN-LAST:event_jLinkButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jLinkButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkButton8ActionPerformed
        int row = jTable1.getSelectedRow();
        if(row<0){
            return;
        }
        int exp = parseExpd(row);
        CanviExpedientDlg dlg = new CanviExpedientDlg(javar.JRDialog.getActiveFrame(), true, exp, cfg.getCoreCfg());
        dlg.setLocationRelativeTo(null);
        dlg.setVisible(true);       
    }//GEN-LAST:event_jLinkButton8ActionPerformed
 
    private void canviaFoto() {
        
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            return;
        }
        int exp2 = parseExpd(row);

           
        String SQL1 = "SELECT Foto FROM `"+CoreCfg.core_mysqlDBPrefix+"`.xes_alumne_detall WHERE EXP_FK_ID="+exp2;
                
        ResultSet rs1 = cfg.getCoreCfg().getMysql().getResultSet(SQL1);
        byte[] foto = null;
        try {
            while(rs1!=null && rs1.next())
            {
                foto = rs1.getBytes("Foto");
            }
         if(rs1!=null) {
                rs1.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(GestionaAlumnes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
       CanviaFoto dlg = new CanviaFoto(javar.JRDialog.getActiveFrame(),true,cfg);      
       dlg.setLocationRelativeTo(null);
       dlg.StartUp(foto, exp2);
       dlg.setVisible(true);
       
       
       
       
    }
    private void fillTable()
    {
        
        int row = jTable1.getSelectedRow();
        int expSelected = -1;
        if(row>=0) 
        {       
            expSelected = parseExpd(row);;
        }
            
        
        while(jTable1.getRowCount()>0) {
            modelTable1.removeRow(0);
        }
        
        
        //Condicions
       
        String condition = " WHERE 1=1 ";
        
        if(jComboBox1.getSelectedIndex()>0)
        {
            condition += " AND xh.ensenyament='"+jComboBox1.getSelectedItem()+"' ";
        }
        if(jComboBox2.getSelectedIndex()>0)
        {
            condition += " AND xh.estudis='"+jComboBox2.getSelectedItem()+"' ";
        }
        if(jComboBox3.getSelectedIndex()>0)
        {
            condition += " AND xh.grup='"+jComboBox3.getSelectedItem()+"' ";
        }
        String search_exp =jTextField1.getText().trim();
        String search_llinatge1 =jTextField2.getText().trim();
        String search_llinatge2 =jTextField3.getText().trim();
        String search_nom1 =jTextField4.getText().trim();
        
        if(search_exp.length() != 0)
        {
              condition += " AND xes.exp2='"+search_exp+"' ";
        }
        if(search_llinatge1.length() != 0)
        {
              condition += " AND xes.llinatge1 LIKE '%"+search_llinatge1+"%' ";
        }
        if(search_llinatge2.length() != 0)
        {
              condition += " AND xes.llinatge2 LIKE '%"+search_llinatge2+"%' ";
        }
        if(search_nom1.length() != 0)
        {
              condition += " AND xes.nom1 LIKE '%"+search_nom1+"%' ";
        }
        
        
        String SQL1 = "SELECT xes.exp2, xes.pwd, concat(xes.llinatge1,' ', xes.llinatge2,', ',xes.nom1) as nom, xes.permisos, xh.estudis, xh.grup, xes.sexe, xd.Foto "
                + " FROM `"+CoreCfg.core_mysqlDBPrefix+"`.xes_alumne as xes INNER JOIN `"+CoreCfg.core_mysqlDBPrefix+"`.xes_alumne_historic as xh ON (xes.exp2=xh.exp2 and xh.anyAcademic='"+cfg.getCoreCfg().anyAcademic+"') "
                + " LEFT JOIN `"+CoreCfg.core_mysqlDBPrefix+"`.xes_alumne_detall as xd on xd.EXP_FK_ID=xes.exp2 "+ condition                
                + " ORDER BY xh.estudis, xh.grup, nom";
        
        ResultSet rs1 = cfg.getCoreCfg().getMysql().getResultSet(SQL1);
        try {
            while(rs1!=null && rs1.next())
            {
                String id= ""+rs1.getInt("exp2");
                String pwd= rs1.getString("pwd");
                String nom=rs1.getString("nom");
                String assignat = rs1.getString("permisos");
                String grup = rs1.getString("estudis")+" "+rs1.getString("grup");
                String anys = "";
                
                JLabel labelExp = new JLabel(id);
                labelExp.setIcon(new ImageIcon(getClass().getResource("/org/iesapp/apps/administrador/icons/delete.gif")));
                
                JLabel cts_grup = new JLabel(grup);
                cts_grup.setToolTipText("Canvia de grup");
                
                JLabel cts_nom = new JLabel(nom);
   
                cts_nom.setToolTipText("Edita les dades personals");
                JLabel cts_assignat = new JLabel(assignat);
     
                cts_assignat.setToolTipText("Edita assignacions");
          
                
                javax.swing.Icon photo = createIcon(rs1.getBytes("Foto"), rowHeight);
                JLabel labelFoto = new JLabel("");
                labelFoto.setToolTipText("Canvia la foto");
                if(photo==null)
                {
                    String resource = "/org/iesapp/apps/administrador/icons/default32x40.png";
                    if(rs1.getString("sexe").equalsIgnoreCase("D")) {
                        resource = "/org/iesapp/apps/administrador/icons/default2_32x40.png";
                    }
                    photo = new javax.swing.ImageIcon(getClass().getResource(resource));
                }
                labelFoto.setIcon(photo);
                
                modelTable1.addRow(new Object[]{labelExp, pwd, cts_grup, cts_nom, labelFoto, cts_assignat, anys});  
            }
            if(rs1!=null) {
                rs1.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(GestionaAlumnes.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel8.setText("S'han trobat "+jTable1.getRowCount()+" resulats");
        
        //torna a seleccionar
        if(expSelected>0)
        {
            for(int i=0; i<jTable1.getRowCount(); i++)
            {
                 int exp2 = parseExpd(i);
                 if(exp2 == expSelected)
                 {
                     jTable1.setRowSelectionInterval(i, i);
                     
                     break;
                 }
            }
        }
    }
    
    
    
    private int parseExpd(int row)
    {
        String tmp = ((JLabel) jTable1.getValueAt(row, 0)).getText();
        return Integer.parseInt(tmp);
    }
      
    public static javax.swing.Icon createIcon(byte[] foto, int heigth2)
    {
        if(foto==null) {
            return null;
        }
        
        java.awt.Image image = java.awt.Toolkit.getDefaultToolkit().createImage(foto);
        java.awt.Image scaledInstance = image.getScaledInstance(-1, heigth2, java.awt.Image.SCALE_DEFAULT);
                
        return new ImageIcon(scaledInstance) ; 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private com.l2fprod.common.swing.JLinkButton jLinkButton1;
    private com.l2fprod.common.swing.JLinkButton jLinkButton2;
    private com.l2fprod.common.swing.JLinkButton jLinkButton3;
    private com.l2fprod.common.swing.JLinkButton jLinkButton4;
    private com.l2fprod.common.swing.JLinkButton jLinkButton5;
    private com.l2fprod.common.swing.JLinkButton jLinkButton6;
    private com.l2fprod.common.swing.JLinkButton jLinkButton7;
    private com.l2fprod.common.swing.JLinkButton jLinkButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.l2fprod.common.swing.JTaskPane jTaskPane1;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup1;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup2;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

   
}
