/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.iesapp.apps.administrador.bimodules;

import com.l2fprod.common.swing.StatusBar;
import java.awt.BorderLayout;
import javax.swing.JMenuBar;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JToolBar;
import org.iesapp.apps.administrador.Cfg;
import org.iesapp.framework.pluggable.StatusBarZone;

/**
 *
 * @author Josep
 */
public class LogModule extends org.iesapp.framework.pluggable.TopModuleWindow {
    private final JProgressBar progressbar;
    private final JToolBar toolbar;
    private final Cfg cfg;

    /**
     * Creates new form LogModule
     */
    public LogModule(JPanel panel3, JProgressBar progressbar, JToolBar toolbar, Cfg cfg) {
        this.cfg = cfg;
        this.moduleDescription = "Administrador de l'iesDigital";
        this.moduleDisplayName = "Administrador";
        this.moduleName = "LogWindow";
    
        initComponents();
        this.setLayout(new BorderLayout());
        this.add(panel3);
        this.progressbar = progressbar;
        this.toolbar = toolbar;
    }

    
     
    @Override
    public void setMenus(JMenuBar jMenuBar1, JToolBar jToolbar1, StatusBar jStatusBar1) {
        ((StatusBarZone) jStatusBar1.getZone("third")).addComponent(progressbar);
        jToolbar1.add(toolbar);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
