/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.iesapp.apps.administrador.bimodules;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.iesapp.apps.mysqlbrowser.MysqlConJPanel;
import org.iesapp.database.MyConnectionBean;
import org.iesapp.framework.pluggable.TopModuleWindow;

/**
 *
 * @author Josep
 * Wrap DBEditor panel into a module
 */
public class MysqlConModule extends TopModuleWindow {
    private  MysqlConJPanel tableEditor;
    

    /**
     * Creates new form DBEditorModule
     */
    public MysqlConModule() {
        this.moduleDescription = "A mysql browser";
        this.moduleDisplayName = "Mysql browser";
        this.moduleName = "mysqlBrowser";
        
        initComponents();
        try {
            tableEditor = new MysqlConJPanel();
            this.add(tableEditor);
        } catch (SQLException ex) {
            Logger.getLogger(MysqlConModule.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
   
    public void setConBean(MyConnectionBean bean)
    {
        try {
            tableEditor.setConBean(bean);
        } catch (SQLException ex) {
            Logger.getLogger(MysqlConModule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getContentContainer().setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
